name: Prod
on:
  push:
    branches:
      - master
jobs:
  cicd:
    name: Deploy master branch to prod environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set docker image
        env:
          REPO: 1234567890.dkr.ecr.us-east-1.amazonaws.com/myapp
          VERSION: 0.1.0
        run: |
          BRANCH=$(echo $GITHUB_REF | cut -d "/" -f 3)
          SHA_SHORT=$(echo $GITHUB_SHA | head -c7)
          echo "export IMAGE=$REPO:$VERSION-$BRANCH.$SHA_SHORT" >> ./env
          cat ./env

      - name: Build image
        uses: ./.github/actions/fargate
        with:
          args: . ./env; docker build -t $IMAGE .

      - name: Login to ECR
        uses: ./.github/actions/fargate
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: login=$(aws ecr get-login --no-include-email) && eval "$login"

      - name: Push image to ECR
        uses: ./.github/actions/fargate
        with:
          args: . ./env; docker push $IMAGE

      - name: Deploy image to fargate
        uses: ./.github/actions/fargate
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FARGATE_CLUSTER: myapp-prod
          FARGATE_SERVICE: myapp-prod
        with:
          args: . ./env; fargate service deploy -i $IMAGE
